### ISSUE TITLE
Bad use of flush interval

### ISSUE THREAD

**Issue by sfc-gh-xhuang** [deltastreaminc/flink-connector-snowflake#19]
I saw the default [buffer flush time](https://github.com/deltastreaminc/flink-connector-snowflake/blob/main/flink-connector-snowflake/src/main/java/io/deltastream/flink/connector/snowflake/sink/config/SnowflakeWriterConfig.java#L37) as 1000ms and min as 10ms. 

I also saw flink checkpointing every 100ms. Then data gets flushed with each checkpoint with [flushOnCheckpoint](https://github.com/deltastreaminc/flink-connector-snowflake/blob/main/flink-connector-snowflake/src/main/java/io/deltastream/flink/connector/snowflake/sink/SnowflakeSinkWriter.java#L125-L135)

Flush is a protected method but looks like it was made accessible via [reflection](https://github.com/deltastreaminc/flink-connector-snowflake/blob/main/flink-connector-snowflake/src/main/java/io/deltastream/flink/connector/snowflake/sink/internal/SnowflakeSinkServiceImpl.java#L328-L346),

This is highly not recommended as the allowed minimum flush internal is 1second from Snowpipe Streaming. Reducing it below 1 second here will create inefficient micro-partitions.

**Comment by mohsenrezaeithe** [comment]
Flush was used as a starter since streaming API documentation didn't suggest any official way of force flushing data (for checkpoint alignment). I had [posted a question in the community](https://community.snowflake.com/s/question/0D5Do00001DAVjyKAH/recommended-ways-to-flush-snowpipe-streaming-buffer-on-demand) to get ideas around a force flush, especially since `close()` is not documented as a way of flushing on demand either.

I do agree that rapid writes come with a cost, but that's also something that's going to be case-by-case. The ramifications of low flush time can be documented on the `SnowflakeSinkBuilder` as a way of educating about the side effects.

**Comment by sfc-gh-xhuang** [comment]
Flush happens automatically every 1 second. Close() is also not recommended as it is better to keep the channel active when there is a continuous stream of data. Opening and closing channels frequently is more taxing than keeping it open. 

In the 2.0.4 release, we have since added a [configuration](https://github.com/snowflakedb/snowflake-ingest-java/pull/586/files) for increasing the flush interval to be higher. But we do not support setting it to be lower than 1 second.
