### ISSUE TITLE
Query related to atleast_once & exactly_once

### ISSUE THREAD

**Issue by prateekkohli21** [deltastreaminc/flink-connector-snowflake#24]
Hi @mohsenrezaeithe, @charles-tan  

I am new to snowflake and flink and wanted to understand how are you achieving atleast once in snowflake connector.

I saw the code and understood that data will be flushed when buffer time expires or when a checkpoint is triggered(by invoking flush method of channel through reflection). Is this sufficient to achieve atleast once gurantee here?

I also saw an issue opened on atleast once, to check the offsets. Is the atleast once gurantee still valid with that issue?
Also, to implement it should we maintain a basic counter for offsets for each channel and pass it with insertRow API and check it after every insert that it has been updated at snowflake or not (but snowflake inserts data either at buffer expiry or checkpoint, so offset will not be updated immediately at snowflake)? So how can we do it?

Also, by any chance have you explored what changes do we need to make to this connector to support exactly once? Because flink needs TwoPhaseCommit supporting sink to support exactly once, but snowflake does not support commiting or rolling back transactions.

Any help is much appreciated, thanks in advance!!

**Comment by charles-tan** [comment]
hi @prateekkohli21 

Yes, we're relying on the flush() call during checkpointing to ensure at least once. If the flush() fails, then the Flink checkpoint will fail and the Flink job will reprocess data starting from the last successful checkpoint.

I think your intuition is correct about checking the offsets. Based on our understanding of the Snowflake flush() mechanism, if it succeeds, then that means everything was written and is enough to satisfy at least once. Checking the offsets will give us further validation, which is why we've ticketed it as an improvement to this connector. Since we force a flush() during checkpointing, we can check for the offsets after the flush() call is complete and it should match our counter of records inserted into Snowpipe.

We have given some thought into exactly once but weren't satisfied with any of the the solutions we thought of. Exactly once semantics work in the Flink Kafka sink connector because Kafka supports creating transactions, as you mentioned, but Snowpipe only exposes the offset which is not enough to do two phase commit.

**Comment by prateekkohli21** [comment]
Thanks for the reply @charles-tan 

But when I try to run atleast once I can see that number of records keep on changing in the snowflake table even after flushing. Which maybe means that it is still has some data in buffers which it is writing to the snowflake table after flush.

I captured below output after calling the flush and just counting the number of records in my table using JDBC:
No of records for checkpoint id : 3 is 45565
No of records for checkpoint id : 3 is 61505
No of records for checkpoint id : 3 is 91825
No of records for checkpoint id : 3 is 91825
No of records for checkpoint id : 3 is 91825

As you can see the it keeps on changing when I execute the count(*) query again and again and settles after sometime.

**Comment by mohsenrezaeithe** [comment]
@prateekkohli21 additional validation for at-least-once was added in [1.0.11-1.18](https://github.com/deltastreaminc/flink-connector-snowflake/releases/tag/1.0.11-1.18). Closing this as there isn't anything else that can be provided in this area.

Please follow up with new issues if you have further questions.
