### ISSUE TITLE
Flink Version Java Version not compatible with AWS

### ISSUE THREAD

**Issue by duncandee** [deltastreaminc/flink-connector-snowflake#29]
AWS supports a minimum of Java 11 and flink recommends Java 11

[Flink](https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/java_compatibility/)
[AWS](https://docs.aws.amazon.com/managed-flink/latest/java/getting-started.html)

I see recently it has been updated to use the experimental version, would it be possible to downgrade this to support the recommended version ?

**Comment by mohsenrezaeithe** [comment]
Hi @duncandee, we haven't considered actively supporting multiple Java versions, and since Java 17 support is becoming more wide spread, we decided to make the jump and go to Java 17. However, we can potentially introduce multiple version builds, and decide what that's going to mean for the versioning, if there's enough interest.

In the meantime, I'm curious if using version `1.0.9-1.17` would be sufficient for your project?

**Comment by duncandee** [comment]
I did consider using it but was worried about any of the bug fixes that have been made since. 
Also if I used it and there was a major issue I would loose out on any support / fixes.

**Comment by mohsenrezaeithe** [comment]
@duncandee We now have a release tree with Java 11 postfixed with `j11` that's going to track the same code base as the main release.

I've pushed `1.0.12rc3-1.18-j11` as a release candidate to test with. Let me know how it goes.

**Comment by duncandee** [comment]
Ah this is amazing.  Thanks so much 🙏🙏
